---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ksflow-io-v1alpha1-kafkaconfig
  failurePolicy: Fail
  name: vkafkaconfig.kb.io
  rules:
  - apiGroups:
    - ksflow.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - kafkaconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ksflow-io-v1alpha1-kafkatopic
  failurePolicy: Fail
  name: vkafkatopic.kb.io
  rules:
  - apiGroups:
    - ksflow.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - kafkatopics
  sideEffects: None
