# permissions for end users to edit kafkaadminclientconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafkaadminclientconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ksflow
    app.kubernetes.io/part-of: ksflow
    app.kubernetes.io/managed-by: kustomize
  name: kafkaadminclientconfig-editor-role
rules:
- apiGroups:
  - ksflow.io
  resources:
  - kafkaadminclientconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ksflow.io
  resources:
  - kafkaadminclientconfigs/status
  verbs:
  - get
