apiVersion: ksflow.io/v1alpha1
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/name: kafkauser
    app.kubernetes.io/instance: kafkauser-sample
    app.kubernetes.io/part-of: ksflow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ksflow
  name: kafkauser-sample
spec:
  # TODO(user): Add fields here
