apiVersion: ksflow.io/v1alpha1
kind: KafkaACL
metadata:
  labels:
    app.kubernetes.io/name: kafkaacl
    app.kubernetes.io/instance: kafkaacl-sample
    app.kubernetes.io/part-of: ksflow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ksflow
  name: kafkaacl-sample
spec:
  # TODO(user): Add fields here
