apiVersion: v1
kind: Service
metadata:
  name: ksflow-quickstart-kafka
  namespace: ksflow-system
spec:
  ports:
  - protocol: TCP
    port: 9092
  selector:
    app: ksflow-quickstart-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksflow-quickstart-kafka
  namespace: ksflow-system
spec:
  selector:
    matchLabels:
      app: ksflow-quickstart-kafka
  template:
    metadata:
      labels:
        app: ksflow-quickstart-kafka
    spec:
      containers:
      - name: kafka
        image: docker.io/bitnami/kafka:3.3.1-debian-11-r19
        env:
        - name: KAFKA_ENABLE_KRAFT
          value: "yes"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://127.0.0.1:9092"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 1@127.0.0.1:9093
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        ports:
        - containerPort: 9092
        livenessProbe:
          tcpSocket:
            port: 9092
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 500m
